# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tech.soa
description: > # this means to ignore newlines until "baseurl:"
  tech.soa is an ecosystem of architectural design technology resources offered to CMU SoA students, faculty, and staff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tech.soa.cmu.edu" # the base hostname & protocol for your site

emptyArray: []

# Build settings
markdown: kramdown
  
collections:
  tutorials:
    output: true

  references:
    output: true
    
  facilities:
    output: true

  softwares:
    output: true
    
  workshops:
    output: true


